// Exercise demo GIFs, vendored from yuhonas/free-exercise-db (Unlicense / public
// domain) — https://github.com/yuhonas/free-exercise-db. Unlike the ExerciseDB
// catalog in exercises.ts, this dataset's images are public domain, so GIFs built
// from its two-frame sequences are included directly under public/exercise-gifs.
//
// Coverage is limited to exercise names used in plans generated by this app so
// far — not the full catalog. Some mappings are the closest available movement
// (e.g. a kettlebell variant standing in for a dumbbell one) rather than an exact
// equipment match; always check form against your own judgment.

const EXERCISE_GIFS: Record<string, string> = {
  "Flat Dumbbell Bench Press": "/exercise-gifs/dumbbell_bench_press.gif",
  "Feet-Elevated Push-ups": "/exercise-gifs/push_ups_with_feet_elevated.gif",
  "Dumbbell Shoulder Press": "/exercise-gifs/dumbbell_shoulder_press.gif",
  "Dumbbell Lateral Raises": "/exercise-gifs/side_lateral_raise.gif",
  "Overhead Dumbbell Tricep Extension":
    "/exercise-gifs/dumbbell_tricep_extension__pronated_grip.gif",
  "Diamond Push-ups": "/exercise-gifs/push_ups___close_triceps_position.gif",
  "Hanging Knee Raises": "/exercise-gifs/hanging_leg_raise.gif",
  Plank: "/exercise-gifs/plank.gif",
  "Pull-ups (or negatives)": "/exercise-gifs/pullups.gif",
  "Pull-ups": "/exercise-gifs/pullups.gif",
  "Bent-Over Dumbbell Row": "/exercise-gifs/bent_over_two_dumbbell_row.gif",
  "One-Arm Dumbbell Row": "/exercise-gifs/one_arm_dumbbell_row.gif",
  "Dumbbell Bicep Curl": "/exercise-gifs/dumbbell_bicep_curl.gif",
  "Dumbbell Goblet Squat": "/exercise-gifs/goblet_squat.gif",
  "Dumbbell Romanian Deadlift":
    "/exercise-gifs/stiff_legged_dumbbell_deadlift.gif",
  "Dumbbell Walking Lunges": "/exercise-gifs/dumbbell_lunges.gif",
  "Bench Step-Ups": "/exercise-gifs/dumbbell_step_ups.gif",
  "Weighted Glute Bridge": "/exercise-gifs/barbell_glute_bridge.gif",
  "Jump Squats": "/exercise-gifs/freehand_jump_squat.gif",
  "Push-ups": "/exercise-gifs/pushups.gif",
  "Mountain Climbers": "/exercise-gifs/mountain_climbers.gif",
  "Russian Twists": "/exercise-gifs/russian_twist.gif",
  "Leg Raises": "/exercise-gifs/flat_bench_lying_leg_raise.gif",
  "Incline Dumbbell Press (bench angled)":
    "/exercise-gifs/incline_dumbbell_press.gif",
  "Arnold Press": "/exercise-gifs/kettlebell_arnold_press.gif",
  "Renegade Rows": "/exercise-gifs/alternating_renegade_row.gif",
  "Hammer Curls": "/exercise-gifs/hammer_curls.gif",
  "Skull Crushers": "/exercise-gifs/lying_dumbbell_tricep_extension.gif",
  "Dumbbell Sumo Squat": "/exercise-gifs/plie_dumbbell_squat.gif",
  "Bulgarian Split Squat (bench)":
    "/exercise-gifs/split_squat_with_dumbbells.gif",
  "Dumbbell Thrusters": "/exercise-gifs/kettlebell_thruster.gif",
};

const NORMALIZED_GIFS: Record<string, string> = Object.fromEntries(
  Object.entries(EXERCISE_GIFS).map(([name, url]) => [
    name.trim().toLowerCase(),
    url,
  ]),
);

/**
 * Exercise labels in a workout split carry their prescription, e.g.
 * "Flat Dumbbell Bench Press — 4×12-15, rest 60s". Strip that off before
 * looking up a GIF.
 */
export function baseExerciseName(label: string): string {
  return label.split(/[—–-]\s*\d/)[0].trim();
}

export function getExerciseGif(label: string): string | null {
  const base = baseExerciseName(label);
  return (
    EXERCISE_GIFS[base] ??
    NORMALIZED_GIFS[base.toLowerCase()] ??
    NORMALIZED_GIFS[label.trim().toLowerCase()] ??
    null
  );
}
